In [ ]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from keras import Sequential
from keras.layers import Dense
from keras.optimizers.legacy import adam

from sklearn.model_selection import train_test_split

In [ ]:
dataset = pd.read_csv('drug200.csv')
dataset.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [ ]:
dataset.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [ ]:
dataset.Sex = dataset.Sex.astype('category').cat.codes
dataset.BP = dataset.BP.astype('category').cat.codes
dataset.Cholesterol = dataset.Cholesterol.astype('category').cat.codes
dataset.head()

Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    0   0            0   25.355  DrugY
1   47    1   1            0   13.093  drugC
2   47    1   1            0   10.114  drugC
3   28    0   2            0    7.798  drugX
4   61    0   1            0   18.043  DrugY

### Handling Empty Values


In [ ]:
dataset.isna().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [ ]:
x = dataset.drop(['Drug'], axis = 1).values
y = pd.get_dummies(dataset.Drug).values
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.3)

print(xTrain.shape)
print(yTrain.shape)

xTrain[:5]

(140, 5)
(140, 5)


array([[21.   ,  0.   ,  0.   ,  1.   , 28.632],
       [43.   ,  1.   ,  0.   ,  0.   , 13.972],
       [49.   ,  1.   ,  0.   ,  1.   ,  8.7  ],
       [67.   ,  1.   ,  2.   ,  1.   ,  9.514],
       [32.   ,  0.   ,  0.   ,  1.   , 10.292]])

## Model Definition Stage

In [ ]:
model = Sequential()
model.add(Dense(5, input_dim = 5, activation = 'relu'))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(16, activation = 'relu'))
model.add(Dense(32, activation = 'relu'))
model.add(Dense(5, activation = 'softmax'))
model.compile(optimizer = adam.Adam(), loss = 'categorical_crossentropy', metrics = ['accuracy'])


In [ ]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_30 (Dense)            (None, 5)                 30        
                                                                 
 dense_31 (Dense)            (None, 16)                96        
                                                                 
 dense_32 (Dense)            (None, 16)                272       
                                                                 
 dense_33 (Dense)            (None, 32)                544       
                                                                 
 dense_34 (Dense)            (None, 5)                 165       
                                                                 
Total params: 1,107
Trainable params: 1,107
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(xTrain, yTrain, epochs = 10)

Epoch 1/10
5/5 [==============================] - 1s 5ms/step - loss: 3.2090 - accuracy: 0.1071
Epoch 2/10
5/5 [==============================] - 0s 6ms/step - loss: 2.5876 - accuracy: 0.1286
Epoch 3/10
5/5 [==============================] - 0s 7ms/step - loss: 2.1554 - accuracy: 0.1857
Epoch 4/10
5/5 [==============================] - 0s 7ms/step - loss: 1.8086 - accuracy: 0.2500
Epoch 5/10
5/5 [==============================] - 0s 7ms/step - loss: 1.6049 - accuracy: 0.3143
Epoch 6/10
5/5 [==============================] - 0s 6ms/step - loss: 1.5113 - accuracy: 0.4786
Epoch 7/10
5/5 [==============================] - 0s 7ms/step - loss: 1.4891 - accuracy: 0.5000
Epoch 8/10
5/5 [==============================] - 0s 6ms/step - loss: 1.4814 - accuracy: 0.5000
Epoch 9/10
5/5 [==============================] - 0s 7ms/step - loss: 1.4539 - accuracy: 0.5000
Epoch 10/10
5/5 [==============================] - 0s 6ms/step - loss: 1.4250 - accuracy: 0.5000


## Model Performance Stage

In [ ]:
yPred = model.predict(xTest)

yPred[:5]

2/2 [==============================] - 0s 6ms/step


array([[0.35718194, 0.1192129 , 0.21689261, 0.03950176, 0.26721078],
       [0.3215536 , 0.15882324, 0.22560854, 0.16829945, 0.12571509],
       [0.3725991 , 0.10420002, 0.21870321, 0.02867647, 0.27582115],
       [0.32772067, 0.14643371, 0.2104638 , 0.06591012, 0.2494717 ],
       [0.30285567, 0.16718027, 0.20254946, 0.0939471 , 0.23346744]],
      dtype=float32)

In [ ]:
yTest[:5]

array([[ True, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True],
       [False, False, False, False,  True],
       [False, False, False, False,  True]])